trigger:
  branches:
    include:
      - main

jobs:
  - job: RetryJob
    displayName: "Job with Retry Mechanism"
    steps:
      - task: Bash@3
        displayName: "Run a Sample Script"
        inputs:
          targetType: 'inline'
          script: |
            echo "Running a task..."
            # Simulate a task failure (exit code 1)
            exit 1
        retryCountOnTaskFailure: 3
